// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package userservice

import (
	"context"

	"go-zero-nacos-demo/user-rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddResp = user.AddResp
	User    = user.User

	UserService interface {
		Add(ctx context.Context, in *User, opts ...grpc.CallOption) (*AddResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Add(ctx context.Context, in *User, opts ...grpc.CallOption) (*AddResp, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}
