// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	UserId   string `json:"userId"`
	Username string `json:"username"`
	Age      int32  `json:"age"`
}

type AddUserResp struct {
	UserId string `json:"userId"`
	Ok     bool   `json:"ok"`
}
